- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
    - !type:CharacterPlaytimeRequirement
      tracker: JobChef
      min: 14400 # DeltaV - 4 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobBartender
      min: 14400 # DeltaV - 4 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobJanitor
      min: 14400 # DeltaV - 4 hours
    - !type:CharacterDepartmentTimeRequirement # DeltaV - Civilian dept time requirement
      department: Civilian
      min: 14400 #Pirate 4 hours
    - !type:CharacterOverallTimeRequirement # DeltaV - Playtime requirement
      min: 72000 #Pirate 20 hours
    - !type:CharacterEmployerRequirement
      employers:
      - NanoTrasen
  weight: 10 # DeltaV - Changed HoP weight from 20 to 10 due to them not being more important than other Heads
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Hydroponics
  - External
  - Cryogenics
  - Lawyer
  - Cargo
  - Boxer # DeltaV - Add Boxer access
  - Clown # DeltaV - Add Clown access
  - Library # DeltaV - Add Library access
  - Mime # DeltaV - Add Mime access
  - Musician # DeltaV - Add Musician access
  - Reporter # DeltaV - Add Reporter access
  - Zookeeper # DeltaV - Add Zookeeper access
  # Goobstation Additions (Re-Adding them back cause screw Delta-V Rules :3)
  - Atmospherics
  - Medical
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Chapel
  - Corpsman
  - Paramedic # DeltaV - Add Paramedic acces
  - Psychologist # DeltaV - Add Psychologist access
  - Mail # Nyanotrasen Addition for Courier
  - Orders # DeltaV - Add Order access
#  - Brig # - Delta-V removed Brig
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: HoPGear
  subGear:
  - HoPPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpackHOPFilled
    shoes: ClothingShoesLeather # DeltaV - HoP needs something better than plebe shoes.
    id: HoPPDA
    ears: ClothingHeadsetHoP # DeltaV - HoP is now a service role, replaces their all channels headset.
  innerClothingSkirt: ClothingUniformJumpskirtHoP
  satchel: ClothingBackpackSatchelHOPFilled
  duffelbag: ClothingBackpackDuffelHOPFilled

- type: startingGear
  id: HoPPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitHoP
    head: ClothingHeadEnvirohelmHoP
    gloves: ClothingHandsGlovesEnviroglovesHoP
