- type: entity
  name: "коробка з наручниками"
  parent: BoxCardboard
  id: BoxHandcuff
  description: "Коробка, повна наручників."
  components:
  - type: Storage
    whitelist:
      components:
      - Handcuff
  - type: StorageFill
    contents:
      - id: Handcuffs
        amount: 4
  - type: Sprite
    layers:
      - state: box_security
      - state: handcuff

- type: entity
  name: "коробка з осліплювачами"
  parent: BoxCardboard
  id: BoxFlashbang
  description: "ПОПЕРЕДЖЕННЯ: Ці пристрої надзвичайно небезпечні і можуть спричинити сліпоту або глухоту при повторному використанні."
  components:
  - type: StorageFill
    contents:
      - id: GrenadeFlashBang
        amount: 4
  - type: Sprite
    layers:
      - state: box_security
      - state: flashbang

- type: entity
  name: "сечуд-бокс"
  parent: BoxCardboard
  id: BoxSechud
  description: "Коробка захисних окулярів."
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesHudSecurity
        amount: 4
  - type: Sprite
    layers:
      - state: box_security
      - state: sechud

- type: entity
  name: "коробка на застібці-блискавці"
  parent: BoxCardboard
  id: BoxZiptie
  description: "Коробка, повна застібок-блискавок."
  components:
  - type: Storage
    grid:
    - 0,0,4,3
    whitelist:
      components:
      - Handcuff
  - type: StorageFill
    contents:
      - id: Zipties
        amount: 10
  - type: Sprite
    layers:
      - state: box_security
      - state: ziptie

- type: entity
  name: "судово-медичний блокнот"
  parent: BoxCardboard
  id: BoxForensicPad
  description: "Коробка криміналістичних прокладок."
  components:
  - type: Item
    shape:
    - 0,0,1,1
  - type: StorageFill
    contents:
    - id: ForensicPad
      amount: 9
  - type: Sprite
    layers:
      - state: box_security
      - state: forensic
