- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requirements:
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
    - !type:CharacterPlaytimeRequirement
      tracker: JobAtmosphericTechnician
      min: 36000 # DeltaV - 10 hours
#    - !type:RoleTimeRequirement # DeltaV - No Station Engineer time requirement
#      role: JobStationEngineer
#      time: 21600 #6 hrs
    - !type:CharacterDepartmentTimeRequirement
      department: Engineering
      min: 90000 # DeltaV - 25 hours
    - !type:CharacterOverallTimeRequirement
      min: 108000 # 30 hours
    - !type:CharacterEmployerRequirement # Added from master-upstream
      employers:
      - NanoTrasen
      - ZavodskoiInterstellar
      - HephaestusIndustries
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellPotato

- type: startingGear
  id: ChiefEngineerGear
  subGear:
  - ChiefEngineerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChiefEngineer
    back: ClothingBackpackChiefEngineerFilled
    shoes: ClothingShoesColorBrown
    id: CEPDA
    ears: ClothingHeadsetAltEngineering # Goobstation
  innerClothingSkirt: ClothingUniformJumpskirtChiefEngineer
  satchel: ClothingBackpackSatchelChiefEngineerFilled
  duffelbag: ClothingBackpackDuffelChiefEngineerFilled

- type: startingGear
  id: ChiefEngineerPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitChiefEngineer
    head: ClothingHeadEnvirohelmChiefEngineer
    gloves: ClothingHandsGlovesEnviroglovesChiefEngineer
