- type: startingGear
  id: RadioGuardGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack
    shoes: ClothingShoesBootsLaceup
    id: SyndiListeningPostPDA
    ears: ClothingHeadsetAltSyndicate
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorPlateCarrierUnremoveable

- type: entity
  parent: ClothingOuterArmorPlateCarrier
  id: ClothingOuterArmorPlateCarrierUnremoveable
  name: "прищеплений носій пластини"
  suffix: Unremoveable
  description: "Готовий носій пластини, який був жорстоко прищеплений до тіла його власника"
  noSpawn: true
  components:
    - type: Unremoveable
