- type: entity
  parent: GunSafe
  id: GunSafePistolUniversal
  name: "сейф для MK32"
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolUniversal
      amount: 2
    - id: MagazineUniversalMagnum
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeSniperGrand
  name: "сейф для рушниць Mark-1"
  components:
  - type: StorageFill
    contents:
    - id: WeaponSniperGrand
      amount: 2
    - id: SpeedLoaderLightRifle
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeVulcanRifle
  name: "вулканічний сейф"
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleVulcan
      amount: 2
    - id: MagazineLightRifle
      amount: 4
      
- type: entity
  parent: GunSafe
  id: GunSafeAdjutantShotgun
  name: "сейф ад'ютантський"
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunAdjutant
      amount: 2
    - id: MagazineShotgun
      amount: 4
      
- type: entity
  parent: GunSafe
  id: GunSafeEnergyGun
  name: "енергетичний сейф для зброї"
  components:
  - type: StorageFill
    contents:
    - id: WeaponEnergyGun
      amount: 3
      
- type: entity
  parent: GunSafe
  id: GunSafeEnergyGunMini
  name: "мініатюрний сейф для енергетичних пістолетів"
  components:
  - type: StorageFill
    contents:
    - id: WeaponEnergyGunMini
      amount: 3
