- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
    - !type:CharacterPlaytimeRequirement
      tracker: JobSalvageSpecialist
      min: 10800 #3 hrs
    - !type:CharacterPlaytimeRequirement # DeltaV - Courier role time requirement
      tracker: JobMailCarrier
      min: 7200 # 2 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Logistics # DeltaV - Logistics Department replacing Cargo
      min: 43200 #DeltaV 12 hours
    - !type:CharacterOverallTimeRequirement
      min: 108000 # 30 hours
    - !type:CharacterEmployerRequirement
      employers:
      - OrionExpress
      - IdrisIncorporated
      - NanoTrasen
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Mail # Nyanotrasen - MailCarrier, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Cargo/mail-carrier.yml
  - Quartermaster
  - Maintenance
  - Command
  - Orders # DeltaV - Orders, see Resources/Prototypes/DeltaV/Access/cargo.yml
  - External # DeltaV - for promoting salvage specialists
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8

- type: startingGear
  id: QuartermasterGear
  subGear:
  - QuartermasterPlasmamanGear
  equipment:
    head: ClothingHeadHatBeretLogi
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackQuartermasterFilled
    shoes: ClothingShoesColorBrown
    id: QuartermasterPDA
    ears: ClothingHeadsetAltCargo # Goobstation
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  innerClothingSkirt: ClothingUniformJumpskirtQM
  satchel: ClothingBackpackSatchelQuartermasterFilled
  duffelbag: ClothingBackpackDuffelQuartermasterFilled

- type: startingGear
  id: QuartermasterPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitQM
    head: ClothingHeadEnvirohelmQM
    gloves: ClothingHandsGlovesEnviroglovesCargo
