- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      min: 54000 # DeltaV - 15 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobForensicMantis
      min: 18000 # 5 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobLibrarian
      min: 18000 # 5 hours
    - !type:CharacterOverallTimeRequirement
      min: 90000 # 25 hours
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - IPC
        - !type:CharacterTraitRequirement
          traits:
            - AnomalousPositronics
        - !type:CharacterTraitRequirement
          inverted: true
          traits:
            - ShadowkinBlackeye
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Robotics #PIRATE
  - Command
  - Maintenance
  - ResearchDirector
  - Mantis # DeltaV - Mantis, see Resources/Prototypes/DeltaV/Access/epistemics.yml
  - Chapel # DeltaV - Chaplain is in Epistemics
  - External # DeltaV - AI satellite access
  - Cryogenics
  special: # Nyanotrasen - Mystagogue can use the Bible
  - !type:AddComponentSpecial
    components:
    - type: BibleUser # Nyano - Lets them heal with bibles
    - type: Psionic # Nyano - They start with telepathic chat
      powerSlots: 3
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: InnatePsionicPowers
        powersToAdd:
          - DispelPower
          - MetapsionicPower
          - TelepathyPower
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: ResearchDirectorGear
  subGear:
  - ResearchDirectorPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackResearchDirectorFilled
    shoes: ClothingShoesColorBrown
    id: RnDPDA
    ears: ClothingHeadsetAltScience # Goobstation
    pocket1: BookPsionicsGuidebook
    pocket2: BibleMystagogue
  innerClothingSkirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelResearchDirectorFilled
  duffelbag: ClothingBackpackDuffelResearchDirectorFilled

- type: startingGear
  id: ResearchDirectorPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitResearchDirector
    head: ClothingHeadEnvirohelmResearchDirector
    gloves: ClothingHandsGlovesEnviroglovesResearchDirector
