- type: entity
  id: ThrusterSecurity
  parent: [ Thruster ]
  name: "рушій"
  suffix: Security
  components:
  - type: Sprite
    sprite: _NF/Structures/Shuttles/thrustersecurity.rsi
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 600  # Considering we need a lot of thrusters didn't want to make an individual one too tanky
      behaviors:
        - !type:DoActsBehavior
          acts: ["Destruction"]
  - type: Machine
    board: ThrusterSecurityMachineCircuitboard

- type: entity
  id: DebugThrusterSecurity
  parent: [DebugThruster]
  name: "рушій"
  suffix: DEBUG, Security
  components:
  - type: Sprite
    sprite: _NF/Structures/Shuttles/thrustersecurity.rsi
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 600  # Considering we need a lot of thrusters didn't want to make an individual one too tanky
      behaviors:
        - !type:DoActsBehavior
          acts: ["Destruction"]
  - type: Machine
    board: ThrusterSecurityMachineCircuitboard

- type: entity
  id: GyroscopeSecurity
  parent: [Gyroscope]
  suffix: Security
  components:
  - type: Sprite
    sprite: _NF/Structures/Shuttles/gyroscope.rsi
    snapCardinals: true
  - type: Machine
    board: GyroscopeSecurityMachineCircuitboard

- type: entity
  id: DebugGyroscopeSecurity
  parent: [DebugGyroscope]
  name: "гіроскоп"
  suffix: DEBUG, Security
  components:
  - type: Sprite
    sprite: _NF/Structures/Shuttles/gyroscope.rsi
    snapCardinals: true
  - type: Machine
    board: GyroscopeSecurityMachineCircuitboard

- type: entity
  id: SmallGyroscopeSecurity
  parent: GyroscopeSecurity
  name: "маленький гіроскоп"
  suffix: Security
  components:
  - type: Thruster
    thrusterType: Angular
    requireSpace: false
    baseThrust: 250
    thrust: 250
  - type: ApcPowerReceiver
    powerLoad: 200
  - type: Sprite
    scale: 0.8, 0.8
    sprite: _NF/Structures/Shuttles/gyroscope.rsi
    snapCardinals: true
  - type: StaticPrice
    price: 100
  - type: Machine
    board: SmallGyroscopeSecurityMachineCircuitboard
